# Ovaj image ima instaliran psql koji trebamo radi loadanja baze
FROM postgres:13

RUN apt-get update
RUN apt-get install pip -y
RUN apt install python3.11-venv -y
RUN apt-get install nano -y
RUN apt install zip -y
RUN apt install unzip -y

# Ako zatreba venv u dockeru ili na serveru
#RUN python3 -m venv .venv
#RUN . .venv/bin/activate
RUN rm /usr/lib/python3.11/EXTERNALLY-MANAGED  # Ovo treba za nekaj, valjda za pip
COPY requirements.txt .
RUN pip install -r requirements.txt

COPY /secrets/.pgpass /root
RUN chmod 0600 /root/.pgpass

RUN mkdir /root/secrets
COPY /secrets/secrets_njuskalo.py /root/secrets/secrets_njuskalo.py
RUN chmod 0600 /root/secrets/secrets_njuskalo.py

# Private key
RUN mkdir -p /.ssh/keys/
COPY /secrets/id_rsa /.ssh/keys/
RUN chmod 400 /.ssh/keys/id_rsa
